[package]
name = "macros-impl"
license = "MIT OR Apache-2.0"
version = "0.0.0"

edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["clone-impls", "extra-traits", "full", "parsing", "printing"] }

[dev-dependencies]
proc-macro-tester = { workspace = true }
