[package]
name = "macros"
license = "MIT OR Apache-2.0"
version = "0.0.0"

edition = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
macros-impl = { workspace = true }

proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
syn = { workspace = true }

[dev-dependencies]
thiserror = { workspace = true }
