//! Miscellaneous utilities

pub mod check_server_block;
pub mod check_word_mute;
pub mod convert_host;
pub mod emoji;
pub mod escape_sql;
pub mod format_milliseconds;
pub mod get_image_size;
pub mod is_quote;
pub mod is_safe_url;
pub mod latest_version;
pub mod note;
pub mod nyaify;
pub mod password;
pub mod random_icon;
pub mod remove_old_attestation_challenges;
pub mod should_nyaify;
pub mod system_info;
pub mod translate;
pub mod user;
