name: CI

on:
  push:
    branches:
      - main    # Se ejecuta en la rama main
      - nvus    # Se ejecuta en la rama nvus
  pull_request:
    branches:
      - main    # Se ejecuta para pull requests a la rama main
      - nvus    # Se ejecuta para pull requests a la rama nvus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.0  

      - name: Install Dependencies
        run: pnpm install  

      - name: Run Tests
        run: pnpm test  

      - name: Build Packages
        run: pnpm run build  
